In [217]:
import pandas as pd
df = pd.read_excel('moods.xlsx')
df

,Date,Happiness,Hopefulness,Sadness,Pain,Guilt/Shame,Anger,Fear/Anxiety,Numb/Empty
0,2022-09-29,2.0,2.0,4.0,2.0,4.0,1.0,3.0,5.0
1,2022-09-30,4.0,3.0,2.0,1.0,2.0,1.0,3.0,3.0
2,2022-10-01,4.0,4.0,2.0,1.0,3.0,1.0,3.0,4.0
3,2022-10-02,4.0,4.0,1.0,1.0,3.0,1.0,4.0,2.0
4,2022-10-03,3.0,2.0,1.0,1.0,4.0,2.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...
183,2023-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,2023-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,2023-04-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,2023-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,2023-04-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [218]:
df = df.dropna()
df

,Date,Happiness,Hopefulness,Sadness,Pain,Guilt/Shame,Anger,Fear/Anxiety,Numb/Empty
0,2022-09-29,2.0,2.0,4.0,2.0,4.0,1.0,3.0,5.0
1,2022-09-30,4.0,3.0,2.0,1.0,2.0,1.0,3.0,3.0
2,2022-10-01,4.0,4.0,2.0,1.0,3.0,1.0,3.0,4.0
3,2022-10-02,4.0,4.0,1.0,1.0,3.0,1.0,4.0,2.0
4,2022-10-03,3.0,2.0,1.0,1.0,4.0,2.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...
170,2023-03-18,7.0,7.0,0.0,3.0,1.0,1.0,2.0,0.0
172,2023-03-20,5.0,5.0,2.0,2.0,2.0,4.0,1.0,3.0
173,2023-03-21,5.0,5.0,1.0,1.0,0.0,0.0,1.0,1.0
174,2023-03-22,6.0,6.0,1.0,2.0,1.0,1.0,1.0,1.0
175,2023-03-23,4.0,4.0,2.0,4.0,2.0,4.0,1.0,3.0

In [219]:
from datetime import datetime

df['Date'] = (pd.to_datetime(df['Date'] + pd.to_timedelta('22:00:00'))).dt.tz_localize('US/Central').dt.tz_convert('UTC')
df.rename(columns={'Date': 'InstantOccurredAt'}, inplace=True)

utc_now = datetime.utcnow()
df['InstantCreatedAt'] = utc_now
df['InstantUpdatedAt'] = utc_now
df

/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/2200599487.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = (pd.to_datetime(df['Date'] + pd.to_timedelta('22:00:00'))).dt.tz_localize('US/Central').dt.tz_convert('UTC')
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/2200599487.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Date': 'InstantOccurredAt'}, inplace=True)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/2200599487.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InstantCreatedAt'] = utc_now
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/2200599487.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InstantUpdatedAt'] = utc_now

,InstantOccurredAt,Happiness,Hopefulness,Sadness,Pain,Guilt/Shame,Anger,Fear/Anxiety,Numb/Empty,InstantCreatedAt,InstantUpdatedAt
0,2022-09-30 03:00:00+00:00,2.0,2.0,4.0,2.0,4.0,1.0,3.0,5.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
1,2022-10-01 03:00:00+00:00,4.0,3.0,2.0,1.0,2.0,1.0,3.0,3.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
2,2022-10-02 03:00:00+00:00,4.0,4.0,2.0,1.0,3.0,1.0,3.0,4.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
3,2022-10-03 03:00:00+00:00,4.0,4.0,1.0,1.0,3.0,1.0,4.0,2.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
4,2022-10-04 03:00:00+00:00,3.0,2.0,1.0,1.0,4.0,2.0,4.0,3.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
...,...,...,...,...,...,...,...,...,...,...,...
170,2023-03-19 03:00:00+00:00,7.0,7.0,0.0,3.0,1.0,1.0,2.0,0.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
172,2023-03-21 03:00:00+00:00,5.0,5.0,2.0,2.0,2.0,4.0,1.0,3.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
173,2023-03-22 03:00:00+00:00,5.0,5.0,1.0,1.0,0.0,0.0,1.0,1.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
174,2023-03-23 03:00:00+00:00,6.0,6.0,1.0,2.0,1.0,1.0,1.0,1.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
175,2023-03-24 03:00:00+00:00,4.0,4.0,2.0,4.0,2.0,4.0,1.0,3.0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296

In [220]:
df['Happiness'] *= 10
df['Hopefulness'] *= 10
df['Sadness'] *= 10
df['Pain'] *= 10
df['Guilt/Shame'] *= 10
df['Anger'] *= 10
df['Fear/Anxiety'] *= 10
df['Numb/Empty'] *= 10

df['Happiness'] = df['Happiness'].astype(int)
df['Hopefulness'] = df['Hopefulness'].astype(int)
df['Sadness'] = df['Sadness'].astype(int)
df['Pain'] = df['Pain'].astype(int)
df['Guilt/Shame'] = df['Guilt/Shame'].astype(int)
df['Anger'] = df['Anger'].astype(int)
df['Fear/Anxiety'] = df['Fear/Anxiety'].astype(int)
df['Numb/Empty'] = df['Numb/Empty'].astype(int)
df

/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Happiness'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hopefulness'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sadness'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pain'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Guilt/Shame'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Anger'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fear/Anxiety'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Numb/Empty'] *= 10
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Happiness'] = df['Happiness'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Hopefulness'] = df['Hopefulness'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sadness'] = df['Sadness'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pain'] = df['Pain'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Guilt/Shame'] = df['Guilt/Shame'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Anger'] = df['Anger'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fear/Anxiety'] = df['Fear/Anxiety'].astype(int)
/var/folders/30/nn2g2pyj05zbp0syzctb9jt40000gn/T/ipykernel_42903/810726265.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Numb/Empty'] = df['Numb/Empty'].astype(int)

,InstantOccurredAt,Happiness,Hopefulness,Sadness,Pain,Guilt/Shame,Anger,Fear/Anxiety,Numb/Empty,InstantCreatedAt,InstantUpdatedAt
0,2022-09-30 03:00:00+00:00,20,20,40,20,40,10,30,50,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
1,2022-10-01 03:00:00+00:00,40,30,20,10,20,10,30,30,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
2,2022-10-02 03:00:00+00:00,40,40,20,10,30,10,30,40,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
3,2022-10-03 03:00:00+00:00,40,40,10,10,30,10,40,20,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
4,2022-10-04 03:00:00+00:00,30,20,10,10,40,20,40,30,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
...,...,...,...,...,...,...,...,...,...,...,...
170,2023-03-19 03:00:00+00:00,70,70,0,30,10,10,20,0,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
172,2023-03-21 03:00:00+00:00,50,50,20,20,20,40,10,30,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
173,2023-03-22 03:00:00+00:00,50,50,10,10,0,0,10,10,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
174,2023-03-23 03:00:00+00:00,60,60,10,20,10,10,10,10,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296
175,2023-03-24 03:00:00+00:00,40,40,20,40,20,40,10,30,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296

In [221]:
df = pd.melt(df, id_vars=['InstantOccurredAt', 'InstantCreatedAt', 'InstantUpdatedAt'], value_vars=['Happiness', 'Hopefulness', 'Sadness', 'Pain', 'Guilt/Shame', 'Anger', 'Fear/Anxiety', 'Numb/Empty'], var_name='Mood', value_name='Magnitude')
df

,InstantOccurredAt,InstantCreatedAt,InstantUpdatedAt,Mood,Magnitude
0,2022-09-30 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Happiness,20
1,2022-10-01 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Happiness,40
2,2022-10-02 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Happiness,40
3,2022-10-03 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Happiness,40
4,2022-10-04 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Happiness,30
...,...,...,...,...,...
1155,2023-03-19 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Numb/Empty,0
1156,2023-03-21 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Numb/Empty,30
1157,2023-03-22 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Numb/Empty,10
1158,2023-03-23 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Numb/Empty,10
1159,2023-03-24 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,Numb/Empty,30

In [222]:
moodLookup = {
	"Happiness": "4911fa6e-1400-4f43-b065-ffc8bd98e216",
	"Hopefulness": "4e8668c9-a34a-45ee-977f-aa64ec22d75a",
	"Sadness": "294bd4b4-bf39-4414-ba1e-b3ddf7908687",
	"Pain": "1d679c4b-dd39-46bf-aebe-b93ac548dbaa",
	"Guilt/Shame": "b28de6d7-ec06-4174-8cc4-44232b707bae",
	"Fear/Anxiety": "88128be8-51d0-4dd3-bff4-93202253ffc3",
	"Numb/Empty": "97d70336-4ac7-4b97-919a-3c52349a0f30",
	"Irritable/Agitated": "82b6d3c6-0cfc-432f-b698-9fa1939358d7",
	"Anger": "0b6fed7e-9e16-453c-950d-13f2b272d560"
}
df = df.replace({'Mood': moodLookup})
df

,InstantOccurredAt,InstantCreatedAt,InstantUpdatedAt,Mood,Magnitude
0,2022-09-30 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,20
1,2022-10-01 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
2,2022-10-02 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
3,2022-10-03 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
4,2022-10-04 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,30
...,...,...,...,...,...
1155,2023-03-19 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,0
1156,2023-03-21 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30
1157,2023-03-22 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10
1158,2023-03-23 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10
1159,2023-03-24 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30

In [223]:
df = df.rename(columns={'Mood': 'MoodId'})
df

,InstantOccurredAt,InstantCreatedAt,InstantUpdatedAt,MoodId,Magnitude
0,2022-09-30 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,20
1,2022-10-01 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
2,2022-10-02 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
3,2022-10-03 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40
4,2022-10-04 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,30
...,...,...,...,...,...
1155,2023-03-19 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,0
1156,2023-03-21 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30
1157,2023-03-22 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10
1158,2023-03-23 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10
1159,2023-03-24 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30

In [224]:
df['UserId'] = '00000000-0000-0000-0000-000000000000'
df['IsArchived'] = False
df

,InstantOccurredAt,InstantCreatedAt,InstantUpdatedAt,MoodId,Magnitude,UserId,IsArchived
0,2022-09-30 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,20,00000000-0000-0000-0000-000000000000,False
1,2022-10-01 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False
2,2022-10-02 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False
3,2022-10-03 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False
4,2022-10-04 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,30,00000000-0000-0000-0000-000000000000,False
...,...,...,...,...,...,...,...
1155,2023-03-19 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,0,00000000-0000-0000-0000-000000000000,False
1156,2023-03-21 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30,00000000-0000-0000-0000-000000000000,False
1157,2023-03-22 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10,00000000-0000-0000-0000-000000000000,False
1158,2023-03-23 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10,00000000-0000-0000-0000-000000000000,False
1159,2023-03-24 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30,00000000-0000-0000-0000-000000000000,False

In [225]:
import uuid

def generate_guid():
    return uuid.uuid4()

df['Id'] = df.apply(lambda x: generate_guid(), axis=1)
df

,InstantOccurredAt,InstantCreatedAt,InstantUpdatedAt,MoodId,Magnitude,UserId,IsArchived,Id
0,2022-09-30 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,20,00000000-0000-0000-0000-000000000000,False,98ebeafe-95e5-460a-ab73-402306e70a85
1,2022-10-01 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False,962123e5-7f28-4f24-bcde-ca3202b0eb01
2,2022-10-02 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False,dc6c7974-4885-45cc-8b52-b85984510e41
3,2022-10-03 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,40,00000000-0000-0000-0000-000000000000,False,a788122f-8c9c-44a6-86a1-ff5612f50ac5
4,2022-10-04 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,4911fa6e-1400-4f43-b065-ffc8bd98e216,30,00000000-0000-0000-0000-000000000000,False,3716b537-579a-4294-86e3-2abee167827f
...,...,...,...,...,...,...,...,...
1155,2023-03-19 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,0,00000000-0000-0000-0000-000000000000,False,cd750aed-0c7d-4143-b9d1-c5040f668bc9
1156,2023-03-21 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30,00000000-0000-0000-0000-000000000000,False,22eefe59-6187-4ce2-ac09-004fdacb8761
1157,2023-03-22 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10,00000000-0000-0000-0000-000000000000,False,9696e03d-c511-4b8e-a965-4bb4ecf0a898
1158,2023-03-23 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,10,00000000-0000-0000-0000-000000000000,False,5ab4fa9f-10b9-494a-8c1f-4dff037620a9
1159,2023-03-24 03:00:00+00:00,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,97d70336-4ac7-4b97-919a-3c52349a0f30,30,00000000-0000-0000-0000-000000000000,False,1cb43419-05bc-402e-8ab7-a69c7022d7ef

In [226]:
df = df.reindex(columns = ['Id','InstantOccurredAt','Magnitude','MoodId','IsArchived','InstantCreatedAt','InstantUpdatedAt','UserId'])

df.to_csv('mood-entries-export.csv',index=False)
df.head()

,Id,InstantOccurredAt,Magnitude,MoodId,IsArchived,InstantCreatedAt,InstantUpdatedAt,UserId
0,98ebeafe-95e5-460a-ab73-402306e70a85,2022-09-30 03:00:00+00:00,20,4911fa6e-1400-4f43-b065-ffc8bd98e216,False,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,00000000-0000-0000-0000-000000000000
1,962123e5-7f28-4f24-bcde-ca3202b0eb01,2022-10-01 03:00:00+00:00,40,4911fa6e-1400-4f43-b065-ffc8bd98e216,False,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,00000000-0000-0000-0000-000000000000
2,dc6c7974-4885-45cc-8b52-b85984510e41,2022-10-02 03:00:00+00:00,40,4911fa6e-1400-4f43-b065-ffc8bd98e216,False,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,00000000-0000-0000-0000-000000000000
3,a788122f-8c9c-44a6-86a1-ff5612f50ac5,2022-10-03 03:00:00+00:00,40,4911fa6e-1400-4f43-b065-ffc8bd98e216,False,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,00000000-0000-0000-0000-000000000000
4,3716b537-579a-4294-86e3-2abee167827f,2022-10-04 03:00:00+00:00,30,4911fa6e-1400-4f43-b065-ffc8bd98e216,False,2023-03-25 04:31:17.058296,2023-03-25 04:31:17.058296,00000000-0000-0000-0000-000000000000